name: Deploy to Remote Server

on:
  push:
    branches: [feat/cicd]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no -p 1203 root@8.219.61.117 'cd /www/wwwroot/bga.blockchainforgood.xyz && git pull origin feat/cicd && docker build --no-cache --memory=1g -t bga:latest . && docker compose down && docker compose up -d'
