name: Deploy to Remote Server

on:
  push:
    branches: [feat/cicd]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no root@8.219.61.117:1203 'cd /www/wwwroot/bga.blockchainforgood.xyz && cat index.html'
