name: Deploy to Remote Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no -p 1203 root@8.219.61.117 'cd /www/wwwroot/www.chainforgood.org && git pull && docker build --memory=1g -t bga:latest . && docker compose up --force-recreate -d'
